### ISSUE TITLE
เปิด Server Microsoft SQL บน Mac OS

### ISSUE THREAD

**Issue by M4R14** [M4R14/markdown-blog#2]
## เปิด Server Microsoft SQL บน Mac OS

เรื่องมันเริ่มต้นจาก ลูกค้าส่ง file .sql มา ขนาด 1.7 G โฮ่….​!! ข้อมูลน่าจะเยอะเเฮะ 
ผมใช้คำสั่ง “vim table_a_b.sql” เพราะมันเปิดดู file ขนาดใหญ่ได้เร็วกว่า Editor ที่มี GUI พอเปิดเสร็จ คุณพรระะะ นี่มันไม่ใช่ SQL แบบเดี่ยวกับ mysql หลงดีใจเห็นว่ามันเป็น .sql เหมือนกันแท้ๆ (ผมลอง import ก็ Error จริงๆด้วย)

ผมตัดสินใจต้องเปิด serve-mssql ขึ้นมาเพื่อ upload file SQL แล้วแปลงเป็น mysql วิธีที่ง่ายที่สุด “docker pull microsoft/mssql-server-linux” เพราะคอมใช้อยู่เป็น mac วิธีนี้สำหรับผมถือว่า WORK!!

```yml
version: '3'
services:
  mssql-server:
    image: microsoft/mssql-server-linux:2017-latest
    restart: always
    volumes:
      - ./sql:/sql
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Mssql123456
    ports:
      - 1433:1433
```

เมื่อ “docker-compose up” เสร็จแล้ว มันจะยังไม่มี database เราต้องเข้าไปสร้างให้มัน แล้วเราจะเข้าไปทำแบบนั้นได้อย่างไร ผมแนะนำ mssql-cli เพราะมันลง mac ได้และก็ตาม Giff ด้านล้างนี่

![image](https://user-images.githubusercontent.com/6532493/55406931-3afb3b80-5587-11e9-91b5-e9a8e0947ec1.png)

ลงเสร็จและก็มาสร้าง DB กัน เริ่มต้นด้วยคำสั่ง “mssql-cli -U sa -P Mssql123456” เเค่นี้ก็จะได้ จอแบบใน Giff ล่ะ ต่อไปก็สร้าง DB ด้วยคำสั่ง style mssql

```sql
USE master;  
GO  
IF DB_ID (N'source_db') IS NOT NULL  
DROP DATABASE source_db;  
GO  
CREATE DATABASE source_db  
COLLATE THAI_CI_AS;  
GO  

--Verify the collation setting.  
SELECT name, collation_name  
FROM sys.databases  
WHERE name = N'source_db';  
GO
```
เป็นอันว่าเราได้ database ชื่อ source_db ที่ใช้ภาษาไทยได้เพราะ “COLLATE THAI_CI_AS” นี่แหละสำคัญ (หาเป็นวันเลยนะ จะบอกให้) ต่อไป file table_a_b.sql ขนาด 1.7G รออยู่

```sh
docker-compose exec mssql-server /opt/mssql-tools/bin/sqlcmd \
-S 127.0.0.1 -U sa -P Mssql123456 \
-d source_db \
-i table_a_b.sql
```

จากนั้นผมไปกินข้าวเที่ยง กลับมาก็ยังไม่เสร็จเลย รออีกเป็น ชม. กว่าจะเสร็จ คือ File นี้มีอยู่ 2 table table แรกมี ~104,000 row(s) table สองมี 1,200,000 row(s) ยังเหลืองาน แปลงเป็น mysql อีกผมทำเสร็จแล้วแหละ ไว้จะเล่าให้ฟัง วันนั้น รวมเวลาที่ใช้ในการ mssql แปลงเป็น mysql แล้วทำให้ผมเลิกงาน เกือบ 4 ทุ่ม~~ เฮ้อ……
